#!/bin/sh

PREREQ="udev"

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

[ -x /sbin/hoopsnake ] || exit 0


run_hoopsnake() {

    # always run configure_networking() before hoopsnake; on NFS
    # mounts this has been done already
    [ "$BOOT" = nfs ] || configure_networking

    log_begin_msg "Starting hoopsnake"

    . /etc/hoopsnake/tailscale_env
    export TS_AUTHKEY TS_API_KEY TS_API_CLIENT_ID TS_API_CLIENT_SECRET TS_BASE_URL

    # using exec and keeping hoopsnake in the foreground enables the
    # init-bottom script to kill the remaining ipconfig processes if
    # someone unlocks the rootfs from the console while the network is
    # being configured
    exec /sbin/hoopsnake -name "$TAILSCALE_SERVICE_NAME" \
        -tsnetVerbose="$TSNET_VERBOSE" \
        -tags="$TAILSCALE_TAGS" \
        -deleteExisting="$TAILSCALE_DELETE_EXISTING"  \
        -maxNodeAge="$TAILSCALE_MAX_NODE_AGE" \
        -authorizedKeys=/etc/hoopsnake/ssh/authorized_keys \
        -hostKey=/etc/hoopsnake/ssh/host_key \
        "$HOOPSNAKE_CMD"
}

if [ -e /etc/hoopsnake/hoopsnake.conf ]; then
    . /etc/hoopsnake/hoopsnake.conf
fi
. /scripts/functions

# On NFS mounts, wait until the network is configured.  On local mounts,
# configure the network in the background (in run_hoopsnake()) so someone
# with console access can enter the passphrase immediately.  (With the
# default ip=dhcp, configure_networking hangs for 5mins or so when the
# network is unavailable, for instance.)
[ "$BOOT" != nfs ] || configure_networking

run_hoopsnake &
echo $! >/run/hoopsnake.pid
